monitortime: 60

maxtimeout: 30
logConfig:
  logFilePath: 'D:/dewuSpider/spiderLog'
  testLogLevel:
    mainLogLevel: INFO
    fileLogLevel: INFO
    consoleLogLevel: INFO
  productLogLevel:
    mainLogLevel: INFO
    fileLogLevel: INFO
    consoleLogLevel: ERROR

db:
  # host: '47.108.128.187'
  host: '127.0.0.1'
  username: 'root'
  password: 'doublez'
  port: 3306
  dbName: 'transaction_data'
  charset: 'utf8'

web:
  host: '127.0.0.1'
  port: '8081'
  domainName:
  imgUrl: '/fileUpload/img'


