monitortime: 60

maxtimeout: 30
logConfig:
  logFilePath: 'logs/'
  testLogLevel:
    mainLogLevel: INFO
    fileLogLevel: INFO
    consoleLogLevel: INFO
  productLogLevel:
    mainLogLevel: INFO
    fileLogLevel: INFO
    consoleLogLevel: ERROR

db:
  host: '47.108.128.187'
  #host: '127.0.0.1'
  username: 'root'
  password: 'doublezx'
  port: 3306
  dbName: 'transaction_data'
  charset: 'utf8'


img_path: /Users/yangshanze/deWu/file/img/
# img_path: /home/deWu/file/img


