monitortime: 60

maxtimeout: 30
logConfig:
  logFilePath: 'app/logs/'
  testLogLevel:
    mainLogLevel: INFO
    fileLogLevel: INFO
    consoleLogLevel: INFO
  productLogLevel:
    mainLogLevel: INFO
    fileLogLevel: INFO
    consoleLogLevel: ERROR

db:
  host: '47.108.128.187'
  # host: '127.0.0.1'
  username: 'root'
  password: 'doublezx'
  port: 3306
  dbName: 'transaction_data'
  charset: 'utf8'


img_path: /home/deWu/file/img/
# img_path: /Users/yangshanze/deWu/file/img/

analysis_img_path: /home/deWu/file/analysis_img/
# analysis_img_path: /Users/yangshanze/deWu/file/analysis_img/

zhi_ma_ip_url: "http://http.tiqu.alicdns.com/getip3?num=1&type=1&pro=&city=0&yys=0&port=11&time=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=1&regions=&gm=4"
# zhiMaIPUrl: "http://http.tiqu.alicdns.com/getip3?num=1&type=1&pro=&city=0&yys=0&port=1&time=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=1&regions=&gm=4"


white_list_ip_url: "http://wapi.http.cnapi.cc/index/index/save_white?neek=107648&appkey=f07559bf5ac83ebbba1971da0a3ad271&white="


